lavc/vvcdec: fix undefined reference to ff_h2645_pixel_aspect
This issue was introduced by commit 1b874555dd35fa6030aab3281712d5ae968253ff

Reproduce steps:
./configure --enable-ffmpeg --disable-everything --enable-decoder=vvc --enable-parser=vvc --enable-demuxer=vvc --enable-protocol=file,pipe --enable-encoder=rawvideo,wrapped_avframe --enable-muxer=rawvideo,md5,null && make -j